name: flutter_map_tile_caching
description: Plugin for flutter_map to provide an easy way to cache tiles and
  download map regions for offline use.
version: 4.0.0-dev.1
repository: https://github.com/JaffaKetchup/flutter_map_tile_caching
documentation: https://github.com/JaffaKetchup/flutter_map_tile_caching/blob/main/README.md
issue_tracker: https://github.com/JaffaKetchup/flutter_map_tile_caching/issues

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  background_fetch: ^1.0.0
  flutter_local_notifications: ^6.0.0
  flutter_map: ^0.13.1
  http: ^0.13.3
  latlong2: ^0.8.0
  meta: ^1.3.0
  network_to_file_image: ^3.0.0
  path: ^1.8.0
  path_provider: ^2.0.2
  permission_handler: ^8.1.2

dev_dependencies: null
flutter: null
